### ISSUE TITLE
Feature Request: Support for TypeScript files

### ISSUE THREAD

**Issue by SwanX1** [Devdre1909/dotenv-intellisence#1]
I really like this extension and have been looking for something like this for a while, however I am unable to use it since I mostly only work on typescript projects. Shouldn't be to hard, right?
I'd PR it myself, however I have no idea how VSC extensions work and I'm afraid I'd mess something up :/

**Comment by Devdre1909** [comment]
Hello, @SwanX1 

Thank you very much, I'd work on that as soon as possible and update you.

**Comment by Devdre1909** [comment]
Hi @SwanX1.

I just added support for typescript files, kindly update the extension.
I'd love to hear your feedback.

**Comment by SwanX1** [comment]
Thank you! It works perfectly, thanks for making this extension, it really helps out with development
