### ISSUE TITLE
Notifications on startup

### ISSUE THREAD

**Issue by juni0r** [Devdre1909/dotenv-intellisence#2]
Hi, 

first of all, thank you for making this extension. I find it immensely useful!

I'd very much appreciate if there were no notifications on startup about discovered .env files.

The general consensus is that VSCode extensions don't show notifications unless there is an error that needs the users attention. If all goes well, they're supposed to start up silently.

For debugging purposes there is a dedicated debug log, where information like 'No .env files found' or 'Error reading .enf file' can go.

Thank you!

**Comment by Devdre1909** [comment]
Hi, @juni0r this is been fixed thanks to @N0ahMC, and the extension has been updated. Kindly update yours too. Enjoy!
